### PR TITLE
Fix fixDeserializeUnsafeFromJava interface for Map

### PR DESCRIPTION
**Pull request by zhixingheyi-tian**

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
Hi @zhouyuan 
This patch can resolve https://github.com/oap-project/gazelle_plugin/issues/788 directly. Without modifying code in Gazelle-plugin.

**Comment by zhouyuan** [comment]
@zhixingheyi-tian  can you also trigger a jenkins job to verify?

**Comment by zhixingheyi-tian** [comment]
> @zhixingheyi-tian can you also trigger a jenkins job to verify?

Triggering

**Comment by zhixingheyi-tian** [comment]
@zhouyuan  
Have verified and triggered Jenkins by https://github.com/oap-project/gazelle_plugin/pull/548,

**Pull request merged**
